##################################################
# EchoService_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.DelAuthServiceModuleWriter
#
##################################################

from EchoService_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class EchoService(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<definitions targetNamespace=\"urn:ndg:security:test:wssecurity\" xmlns=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:tns=\"urn:ndg:security:test:wssecurity\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">
  <types>
  <xsd:schema elementFormDefault=\"qualified\" targetNamespace=\"urn:ndg:security:test:wssecurity\">
      <xsd:element name=\"Echo\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"EchoIn\" type=\"xsd:string\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name=\"EchoResponse\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"EchoResult\" type=\"xsd:string\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
  </xsd:schema>
  </types>

  <message name=\"EchoInputMsg\">
    <part element=\"tns:Echo\" name=\"parameters\"/>
  </message>
  <message name=\"EchoOutputMsg\">
    <part element=\"tns:EchoResponse\" name=\"parameters\"/>
  </message>

  <portType name=\"Echo\">
    <operation name=\"Echo\">
      <input message=\"tns:EchoInputMsg\"/>
      <output message=\"tns:EchoOutputMsg\"/>
    </operation>
  </portType>

  <binding name=\"EchoBinding\" type=\"tns:Echo\">
    <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
    <operation name=\"Echo\">
      <soap:operation soapAction=\"Echo\"/>
	<input>
   	  <soap:body use=\"literal\"/> 
	</input>
	<output>
	  <soap:body use=\"literal\"/> 
	</output>
    </operation>
  </binding>

  <service name=\"EchoService\">
    <port binding=\"tns:EchoBinding\" name=\"Echo\">
      <soap:address location=\"http://localhost:7100\"/>
    </port>
  </service>

</definitions>"""

    def __init__(self, post='', **kw):
        ServiceSOAPBinding.__init__(self, post)
        if kw.has_key('impl'):
            self.impl = kw['impl']
        self.auth_method_name = None
        if kw.has_key('auth_method_name'):
            self.auth_method_name = kw['auth_method_name']
    def authorize(self, auth_info, post, action):
        if self.auth_method_name and hasattr(self.impl, self.auth_method_name):
            return getattr(self.impl, self.auth_method_name)(auth_info, post, action)
        else:
            return 1

    def soap_Echo(self, ps):
        self.request = ps.Parse(EchoInputMsg.typecode)
        parameters = self.request._EchoIn

        # If we have an implementation object use it
        if hasattr(self,'impl'):
            parameters = self.impl.Echo(parameters)

        result = EchoOutputMsg()
        # If we have an implementation object, copy the result 
        if hasattr(self,'impl'):
            result._EchoResult = parameters
        return result

    soapAction['Echo'] = 'soap_Echo'
    root[(EchoInputMsg.typecode.nspname,EchoInputMsg.typecode.pname)] = 'soap_Echo'

