################################################## 
# EchoServer_messages.py 
# generated by ZSI.generate.wsdl2python
##################################################


from EchoServer_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

EchoRequest = urn_ZSI_examples.Echo().pyclass

EchoResponse = urn_ZSI_examples.EchoResponse().pyclass

EchoEncrRequest = urn_ZSI_examples.EchoEncr().pyclass

EchoEncrResponse = urn_ZSI_examples.EchoEncrResponse().pyclass
