################################################## 
# EchoServer_client.py 
# generated by ZSI.generate.wsdl2python
##################################################



import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

from EchoServer_messages import *

# Locator
class EchoServerLocator:
    EchoServer_address = "http://localhost:7100"
    def getEchoServerAddress(self):
        return EchoServerLocator.EchoServer_address
    def getEchoServer(self, url=None, **kw):
        return EchoServerSOAP(url or EchoServerLocator.EchoServer_address, **kw)

# Methods
class EchoServerSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb77f40ec>
    def Echo(self, EchoIn):

        request = EchoRequest()
        request.EchoIn = EchoIn

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="Echo", **kw)
        # no output wsaction
        response = self.binding.Receive(EchoResponse.typecode)
        EchoResult = response.EchoResult
        return EchoResult

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb77f48cc>
    def EchoEncr(self, EchoIn):

        request = EchoEncrRequest()
        request.EchoIn = EchoIn

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="EchoEncr", **kw)
        # no output wsaction
        response = self.binding.Receive(EchoEncrResponse.typecode)
        EchoResult = response.EchoResult
        return EchoResult
