################################################## 
# attAuthority_services.py 
# generated by ZSI.wsdl2python 
# 
# 
##################################################


import urlparse, types
from ZSI.TCcompound import Struct
from ZSI import client
import ZSI

class attAuthorityServiceInterface:
    def getattAuthority(self, portAddress=None, **kw):
        raise NonImplementationError, "method not implemented"


class attAuthorityServiceLocator(attAuthorityServiceInterface):
    attAuthority_address = ""
    def getattAuthorityAddress(self):
        return attAuthorityServiceLocator.attAuthority_address

    def getattAuthority(self, portAddress=None, **kw):
        return attAuthorityBindingSOAP(portAddress or attAuthorityServiceLocator.attAuthority_address, **kw)


class attAuthorityBindingSOAP:

    def __init__(self, addr, **kw):
        netloc = (urlparse.urlparse(addr)[1]).split(":") + [80,]
        if not kw.has_key("host"):
            kw["host"] = netloc[0]
        if not kw.has_key("port"):
            kw["port"] = int(netloc[1])
        if not kw.has_key("url"):
            kw["url"] =  urlparse.urlparse(addr)[2]
        self.binding = client.Binding(**kw)


    def getHostInfo(self, request):
        """
        @param: request to hostInfoRequest::
          _hostInfoReq: str

        @return: response from hostInfoResponse::
          _hostInfoResp: str
        """

        if not isinstance(request, hostInfoRequest) and\
            not issubclass(hostInfoRequest, request.__class__):
            raise TypeError, "%s incorrect request type" %(request.__class__)
        kw = {}
        response = self.binding.Send(None, None, request, soapaction="urn:attAuthority#getHostInfo", **kw)
        response = self.binding.Receive(hostInfoResponseWrapper())
        if not isinstance(response, hostInfoResponse) and\
            not issubclass(hostInfoResponse, response.__class__):
            raise TypeError, "%s incorrect response type" %(response.__class__)
        return response


    def getPubKey(self, request):
        """
        @param: request to pubKeyRequest::
          _pubKeyReq: str

        @return: response from pubKeyResponse::
          _pubKeyResp: str
        """

        if not isinstance(request, pubKeyRequest) and\
            not issubclass(pubKeyRequest, request.__class__):
            raise TypeError, "%s incorrect request type" %(request.__class__)
        kw = {}
        response = self.binding.Send(None, None, request, soapaction="urn:attAuthority#getPubKey", **kw)
        response = self.binding.Receive(pubKeyResponseWrapper())
        if not isinstance(response, pubKeyResponse) and\
            not issubclass(pubKeyResponse, response.__class__):
            raise TypeError, "%s incorrect response type" %(response.__class__)
        return response


    def getTrustedHostInfo(self, request):
        """
        @param: request to trustedHostInfoRequest::
          _trustedHostInfoReq: str

        @return: response from trustedHostInfoResponse::
          _trustedHostInfoResp: str
        """

        if not isinstance(request, trustedHostInfoRequest) and\
            not issubclass(trustedHostInfoRequest, request.__class__):
            raise TypeError, "%s incorrect request type" %(request.__class__)
        kw = {}
        response = self.binding.Send(None, None, request, soapaction="urn:attAuthority#getTrustedHostInfo", **kw)
        response = self.binding.Receive(trustedHostInfoResponseWrapper())
        if not isinstance(response, trustedHostInfoResponse) and\
            not issubclass(trustedHostInfoResponse, response.__class__):
            raise TypeError, "%s incorrect response type" %(response.__class__)
        return response


    def reqAuthorisation(self, request):
        """
        @param: request to authorisationRequest::
          _authorisationReq: str

        @return: response from authorisationResponse::
          _authorisationResp: str
        """

        if not isinstance(request, authorisationRequest) and\
            not issubclass(authorisationRequest, request.__class__):
            raise TypeError, "%s incorrect request type" %(request.__class__)
        kw = {}
        response = self.binding.Send(None, None, request, soapaction="urn:attAuthority#reqAuthorisation", **kw)
        response = self.binding.Receive(authorisationResponseWrapper())
        if not isinstance(response, authorisationResponse) and\
            not issubclass(authorisationResponse, response.__class__):
            raise TypeError, "%s incorrect response type" %(response.__class__)
        return response



class authorisationRequest (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._authorisationReq = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, authorisationRequest, [ZSI.TC.String(pname="authorisationReq",aname="_authorisationReq",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class authorisationRequestWrapper(authorisationRequest):
    """wrapper for rpc:encoded message"""

    typecode = authorisationRequest(name='reqAuthorisation', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        authorisationRequest.__init__( self, name='reqAuthorisation', ns='urn:attAuthority' )

class authorisationResponse (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._authorisationResp = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, authorisationResponse, [ZSI.TC.String(pname="authorisationResp",aname="_authorisationResp",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class authorisationResponseWrapper(authorisationResponse):
    """wrapper for rpc:encoded message"""

    typecode = authorisationResponse(name='reqAuthorisationResponse', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        authorisationResponse.__init__( self, name='reqAuthorisationResponse', ns='urn:attAuthority' )

class hostInfoRequest (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._hostInfoReq = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, hostInfoRequest, [ZSI.TC.String(pname="hostInfoReq",aname="_hostInfoReq",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class hostInfoRequestWrapper(hostInfoRequest):
    """wrapper for rpc:encoded message"""

    typecode = hostInfoRequest(name='getHostInfo', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        hostInfoRequest.__init__( self, name='getHostInfo', ns='urn:attAuthority' )

class hostInfoResponse (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._hostInfoResp = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, hostInfoResponse, [ZSI.TC.String(pname="hostInfoResp",aname="_hostInfoResp",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class hostInfoResponseWrapper(hostInfoResponse):
    """wrapper for rpc:encoded message"""

    typecode = hostInfoResponse(name='getHostInfoResponse', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        hostInfoResponse.__init__( self, name='getHostInfoResponse', ns='urn:attAuthority' )

class pubKeyRequest (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._pubKeyReq = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, pubKeyRequest, [ZSI.TC.String(pname="pubKeyReq",aname="_pubKeyReq",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class pubKeyRequestWrapper(pubKeyRequest):
    """wrapper for rpc:encoded message"""

    typecode = pubKeyRequest(name='getPubKey', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        pubKeyRequest.__init__( self, name='getPubKey', ns='urn:attAuthority' )

class pubKeyResponse (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._pubKeyResp = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, pubKeyResponse, [ZSI.TC.String(pname="pubKeyResp",aname="_pubKeyResp",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class pubKeyResponseWrapper(pubKeyResponse):
    """wrapper for rpc:encoded message"""

    typecode = pubKeyResponse(name='getPubKeyResponse', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        pubKeyResponse.__init__( self, name='getPubKeyResponse', ns='urn:attAuthority' )

class trustedHostInfoRequest (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._trustedHostInfoReq = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, trustedHostInfoRequest, [ZSI.TC.String(pname="trustedHostInfoReq",aname="_trustedHostInfoReq",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class trustedHostInfoRequestWrapper(trustedHostInfoRequest):
    """wrapper for rpc:encoded message"""

    typecode = trustedHostInfoRequest(name='getTrustedHostInfo', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        trustedHostInfoRequest.__init__( self, name='getTrustedHostInfo', ns='urn:attAuthority' )

class trustedHostInfoResponse (ZSI.TCcompound.Struct): 
    def __init__(self, name=None, ns=None):
        self._trustedHostInfoResp = None

        oname = None
        if name:
            oname = name
            if ns:
                oname += ' xmlns="%s"' % ns
            ZSI.TC.Struct.__init__(self, trustedHostInfoResponse, [ZSI.TC.String(pname="trustedHostInfoResp",aname="_trustedHostInfoResp",optional=1),], pname=name, aname="_%s" % name, oname=oname )

class trustedHostInfoResponseWrapper(trustedHostInfoResponse):
    """wrapper for rpc:encoded message"""

    typecode = trustedHostInfoResponse(name='getTrustedHostInfoResponse', ns='urn:attAuthority')
    def __init__( self, name=None, ns=None, **kw ):
        trustedHostInfoResponse.__init__( self, name='getTrustedHostInfoResponse', ns='urn:attAuthority' )
