################################################## 
# VocabServerAPI_dlService_messages.py 
# generated by ZSI.generate.wsdl2python
##################################################


from VocabServerAPI_dlService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

whatListsRequest = urn_VocabServerAPI_dl.whatLists().pyclass

whatListsResponse = urn_VocabServerAPI_dl.whatListsResponse().pyclass

getListRequest = urn_VocabServerAPI_dl.getList().pyclass

getListResponse = urn_VocabServerAPI_dl.getListResponse().pyclass

verifyTermRequest = urn_VocabServerAPI_dl.verifyTerm().pyclass

verifyTermResponse = urn_VocabServerAPI_dl.verifyTermResponse().pyclass

pvMapRequest = urn_VocabServerAPI_dl.pvMap().pyclass

pvMapResponse = urn_VocabServerAPI_dl.pvMapResponse().pyclass

getPhenomDictRequest = urn_VocabServerAPI_dl.getPhenomDict().pyclass

getPhenomDictResponse = urn_VocabServerAPI_dl.getPhenomDictResponse().pyclass

whatListsCatRequest = urn_VocabServerAPI_dl.whatListsCat().pyclass

whatListsCatResponse = urn_VocabServerAPI_dl.whatListsCatResponse().pyclass

searchVocabRequest = urn_VocabServerAPI_dl.searchVocab().pyclass

searchVocabResponse = urn_VocabServerAPI_dl.searchVocabResponse().pyclass
