################################################## 
# VocabServerAPIService_services_types.py 
# generated by ZSI.generate.wsdl2python
##################################################


import ZSI
import ZSI.TCcompound
from ZSI.TC import ElementDeclaration,TypeDefinition
from ZSI.TC import _get_type_definition as GTD, _get_global_element_declaration as GED

##############################
# targetNamespace
# urn:VocabServerAPI
##############################

class urn_VocabServerAPI:
    targetNamespace = "urn:VocabServerAPI"

    class whatLists(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "whatLists"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.whatLists.schema
            TClist = [ZSI.TC.String(pname=(ns,"in0"), aname="in0", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","whatLists")
            kw["aname"] = "whatLists"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.in0 = None
                    return
            Holder.__name__ = "whatLists_Holder"
            self.pyclass = Holder

    class whatListsResponse(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "whatListsResponse"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.whatListsResponse.schema
            TClist = [ZSI.TC.String(pname=(ns,"whatListsReturn"), aname="whatListsReturn", minOccurs=1, maxOccurs="unbounded", nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","whatListsResponse")
            kw["aname"] = "whatListsResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.whatListsReturn = []
                    return
            Holder.__name__ = "whatListsResponse_Holder"
            self.pyclass = Holder

    class getList(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "getList"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.getList.schema
            TClist = [ZSI.TC.String(pname=(ns,"in0"), aname="in0", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in1"), aname="in1", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in2"), aname="in2", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","getList")
            kw["aname"] = "getList"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.in0 = None
                    self.in1 = None
                    self.in2 = None
                    return
            Holder.__name__ = "getList_Holder"
            self.pyclass = Holder

    class getListResponse(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "getListResponse"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.getListResponse.schema
            TClist = [ZSI.TC.String(pname=(ns,"getListReturn"), aname="getListReturn", minOccurs=1, maxOccurs="unbounded", nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","getListResponse")
            kw["aname"] = "getListResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.getListReturn = []
                    return
            Holder.__name__ = "getListResponse_Holder"
            self.pyclass = Holder

    class verifyTerm(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "verifyTerm"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.verifyTerm.schema
            TClist = [ZSI.TC.String(pname=(ns,"in0"), aname="in0", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in1"), aname="in1", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in2"), aname="in2", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","verifyTerm")
            kw["aname"] = "verifyTerm"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.in0 = None
                    self.in1 = None
                    self.in2 = None
                    return
            Holder.__name__ = "verifyTerm_Holder"
            self.pyclass = Holder

    class verifyTermResponse(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "verifyTermResponse"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.verifyTermResponse.schema
            TClist = [ZSI.TC.String(pname=(ns,"verifyTermReturn"), aname="verifyTermReturn", minOccurs=1, maxOccurs="unbounded", nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","verifyTermResponse")
            kw["aname"] = "verifyTermResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.verifyTermReturn = []
                    return
            Holder.__name__ = "verifyTermResponse_Holder"
            self.pyclass = Holder

    class pvMap(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "pvMap"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.pvMap.schema
            TClist = [ZSI.TC.String(pname=(ns,"in0"), aname="in0", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in1"), aname="in1", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in2"), aname="in2", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","pvMap")
            kw["aname"] = "pvMap"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.in0 = None
                    self.in1 = None
                    self.in2 = None
                    return
            Holder.__name__ = "pvMap_Holder"
            self.pyclass = Holder

    class pvMapResponse(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "pvMapResponse"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.pvMapResponse.schema
            TClist = [ZSI.TC.String(pname=(ns,"pvMapReturn"), aname="pvMapReturn", minOccurs=1, maxOccurs="unbounded", nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","pvMapResponse")
            kw["aname"] = "pvMapResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.pvMapReturn = []
                    return
            Holder.__name__ = "pvMapResponse_Holder"
            self.pyclass = Holder

    class getPhenomDict(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "getPhenomDict"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.getPhenomDict.schema
            TClist = [ZSI.TC.String(pname=(ns,"in0"), aname="in0", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","getPhenomDict")
            kw["aname"] = "getPhenomDict"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.in0 = None
                    return
            Holder.__name__ = "getPhenomDict_Holder"
            self.pyclass = Holder

    class getPhenomDictResponse(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "getPhenomDictResponse"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.getPhenomDictResponse.schema
            TClist = [ZSI.TC.String(pname=(ns,"getPhenomDictReturn"), aname="getPhenomDictReturn", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","getPhenomDictResponse")
            kw["aname"] = "getPhenomDictResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.getPhenomDictReturn = None
                    return
            Holder.__name__ = "getPhenomDictResponse_Holder"
            self.pyclass = Holder

    class whatListsCat(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "whatListsCat"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.whatListsCat.schema
            TClist = []
            kw["pname"] = ("urn:VocabServerAPI","whatListsCat")
            kw["aname"] = "whatListsCat"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    return
            Holder.__name__ = "whatListsCat_Holder"
            self.pyclass = Holder

    class whatListsCatResponse(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "whatListsCatResponse"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.whatListsCatResponse.schema
            TClist = [ZSI.TC.String(pname=(ns,"whatListsCatReturn"), aname="whatListsCatReturn", minOccurs=1, maxOccurs="unbounded", nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","whatListsCatResponse")
            kw["aname"] = "whatListsCatResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.whatListsCatReturn = []
                    return
            Holder.__name__ = "whatListsCatResponse_Holder"
            self.pyclass = Holder

    class searchVocab(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "searchVocab"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.searchVocab.schema
            TClist = [ZSI.TC.String(pname=(ns,"in0"), aname="in0", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in1"), aname="in1", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"in2"), aname="in2", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","searchVocab")
            kw["aname"] = "searchVocab"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.in0 = None
                    self.in1 = None
                    self.in2 = None
                    return
            Holder.__name__ = "searchVocab_Holder"
            self.pyclass = Holder

    class searchVocabResponse(ZSI.TCcompound.ComplexType, ElementDeclaration):
        schema = "urn:VocabServerAPI"
        literal = "searchVocabResponse"
        def __init__(self, **kw):
            ns = urn_VocabServerAPI.searchVocabResponse.schema
            TClist = [ZSI.TC.String(pname=(ns,"searchVocabReturn"), aname="searchVocabReturn", minOccurs=1, maxOccurs="unbounded", nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("urn:VocabServerAPI","searchVocabResponse")
            kw["aname"] = "searchVocabResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self.searchVocabReturn = []
                    return
            Holder.__name__ = "searchVocabResponse_Holder"
            self.pyclass = Holder

# end class urn_VocabServerAPI (tns: urn:VocabServerAPI)
