################################################## 
# SimpleCA_messages.py 
# generated by ZSI.generate.wsdl2python
##################################################


from SimpleCA_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

certRequest = urn_ZSI_SimpleCA.certReq().pyclass

certResponse = urn_ZSI_SimpleCA.certReqResponse().pyclass
