"""ZSI autogenerated code from WSDL for Attribute Authority SOAP interface

NERC Data Grid Project

"""
__author__ = "P J Kershaw"
__date__ = "01/10/08"
__copyright__ = "(C) 2009 Science and Technology Facilities Council"
__contact__ = "Philip.Kershaw@stfc.ac.uk"
__revision__ = "$Id$"
