################################################## 
# AttAuthority_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from AttAuthority_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class AttAuthorityServiceLocator:
    AttAuthority_address = "http://localhost:5700"
    def getAttAuthorityAddress(self):
        return AttAuthorityServiceLocator.AttAuthority_address
    def getAttAuthority(self, url=None, **kw):
        return AttAuthorityBindingSOAP(url or AttAuthorityServiceLocator.AttAuthority_address, **kw)

# Methods
class AttAuthorityBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb7850dac>
    def getAttCert(self, userCert):

        request = getAttCertInputMsg()
        request._userCert = userCert

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getAttCert", **kw)
        # no output wsaction
        response = self.binding.Receive(getAttCertOutputMsg.typecode)
        attCert = response._attCert
        return attCert

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb785526c>
    def getHostInfo(self):

        request = getHostInfoInputMsg()

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getHostInfo", **kw)
        # no output wsaction
        response = self.binding.Receive(getHostInfoOutputMsg.typecode)
        return 

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb7855a0c>
    def getTrustedHostInfo(self, role):

        request = getTrustedHostInfoInputMsg()
        request._role = role

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getTrustedHostInfo", **kw)
        # no output wsaction
        response = self.binding.Receive(getTrustedHostInfoOutputMsg.typecode)
        trustedHosts = response._trustedHosts
        return trustedHosts

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb7855b8c>
    def getCert(self):

        request = getPubKeyInputMsg()

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getPubKey", **kw)
        # no output wsaction
        response = self.binding.Receive(getPubKeyOutputMsg.typecode)
        x509Cert = response._x509Cert
        return x509Cert

getAttCertInputMsg = ns0.getAttCert_Dec().pyclass

getAttCertOutputMsg = ns0.getAttCertResponse_Dec().pyclass

getHostInfoInputMsg = ns0.getHostInfo_Dec().pyclass

getHostInfoOutputMsg = ns0.getHostInfoResponse_Dec().pyclass

getTrustedHostInfoInputMsg = ns0.getTrustedHostInfo_Dec().pyclass

getTrustedHostInfoOutputMsg = ns0.getTrustedHostInfoResponse_Dec().pyclass

getPubKeyInputMsg = ns0.getPubKey_Dec().pyclass

getPubKeyOutputMsg = ns0.getPubKeyResponse_Dec().pyclass
