################################################## 
# AttributeAuthority_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from AttributeAuthority_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class AttributeAuthorityServiceLocator:
    AttributeAuthority_address = "http://localhost:5000"
    def getAttributeAuthorityAddress(self):
        return AttributeAuthorityServiceLocator.AttributeAuthority_address
    def getAttributeAuthority(self, url=None, **kw):
        return AttributeAuthorityBindingSOAP(url or AttributeAuthorityServiceLocator.AttributeAuthority_address, **kw)

# Methods
class AttributeAuthorityBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x84cad2c>
    def getAttCert(self, userId,userX509Cert,userAttCert):

        request = getAttCertInputMsg()
        request._userId = userId
        request._userX509Cert = userX509Cert
        request._userAttCert = userAttCert

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getAttCert", **kw)
        # no output wsaction
        response = self.binding.Receive(getAttCertOutputMsg.typecode)
        attCert = response._attCert
        msg = response._msg
        return attCert,msg

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x84d106c>
    def getHostInfo(self):

        request = getHostInfoInputMsg()

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getHostInfo", **kw)
        # no output wsaction
        response = self.binding.Receive(getHostInfoOutputMsg.typecode)
        hostname = response._hostname
        siteName = response._siteName
        aaURI = response._aaURI
        aaDN = response._aaDN
        loginURI = response._loginURI
        loginServerDN = response._loginServerDN
        loginRequestServerDN = response._loginRequestServerDN
        return hostname,siteName,aaURI,aaDN,loginURI,loginServerDN,loginRequestServerDN

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x84d1c0c>
    def getTrustedHostInfo(self, role):

        request = getTrustedHostInfoInputMsg()
        request._role = role

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getTrustedHostInfo", **kw)
        # no output wsaction
        response = self.binding.Receive(getTrustedHostInfoOutputMsg.typecode)
        trustedHosts = response._trustedHosts
        return trustedHosts

    # op: <ZSI.wstools.WSDLTools.Message instance at 0x84d1d8c>
    def getAllHostsInfo(self):

        request = getAllHostsInfoInputMsg()

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="getAllHostsInfo", **kw)
        # no output wsaction
        response = self.binding.Receive(getAllHostsInfoOutputMsg.typecode)
        hosts = response._hosts
        return hosts

getAttCertInputMsg = ns0.getAttCert_Dec().pyclass

getAttCertOutputMsg = ns0.getAttCertResponse_Dec().pyclass

getHostInfoInputMsg = ns0.getHostInfo_Dec().pyclass

getHostInfoOutputMsg = ns0.getHostInfoResponse_Dec().pyclass

getTrustedHostInfoInputMsg = ns0.getTrustedHostInfo_Dec().pyclass

getTrustedHostInfoOutputMsg = ns0.getTrustedHostInfoResponse_Dec().pyclass

getAllHostsInfoInputMsg = ns0.getAllHostsInfo_Dec().pyclass

getAllHostsInfoOutputMsg = ns0.getAllHostsInfoResponse_Dec().pyclass
