##################################################
# AttributeAuthority_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.DelAuthServiceModuleWriter
#
##################################################

from ndg.security.common.zsi.attributeauthority.AttributeAuthority_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class AttributeAuthorityService(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions name=\"AttributeAuthority\" targetNamespace=\"urn:ndg:security:AttributeAuthority\" xmlns=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:tns=\"urn:ndg:security:AttributeAuthority\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">

  <wsdl:types>
    <xsd:schema targetNamespace=\"urn:ndg:security:AttributeAuthority\">
    
      <xsd:complexType name=\"HostInfo\">
        <xsd:sequence>
          <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"hostname\" type=\"xsd:string\"/>
          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"siteName\" type=\"xsd:string\"/>
          <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"aaURI\" type=\"xsd:string\"/>
          <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"aaDN\" type=\"xsd:string\"/>
          <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"loginURI\" type=\"xsd:string\"/>
          <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"loginServerDN\" type=\"xsd:string\"/>
          <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"loginRequestServerDN\" type=\"xsd:string\"/>
          <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"roleList\" type=\"xsd:string\"/>
        </xsd:sequence>
      </xsd:complexType>
      
      <xsd:element name=\"getAttCert\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"userId\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"userX509Cert\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"userAttCert\" type=\"xsd:string\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      
      <xsd:element name=\"getAttCertResponse\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"attCert\" type=\"xsd:string\"/>
	        <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"msg\" type=\"xsd:string\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name=\"getHostInfo\">
        <xsd:complexType/>
      </xsd:element>

      <xsd:element name=\"getHostInfoResponse\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"hostname\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"siteName\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"aaURI\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"aaDN\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"loginURI\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"loginServerDN\" type=\"xsd:string\"/>
            <xsd:element maxOccurs=\"1\" minOccurs=\"1\" name=\"loginRequestServerDN\" type=\"xsd:string\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name=\"getTrustedHostInfo\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"role\" type=\"xsd:string\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name=\"getTrustedHostInfoResponse\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"trustedHosts\" type=\"tns:HostInfo\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name=\"getAllHostsInfo\">
        <xsd:complexType/>
      </xsd:element>

      <xsd:element name=\"getAllHostsInfoResponse\">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"hosts\" type=\"tns:HostInfo\"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
 
  <wsdl:message name=\"getAttCertInputMsg\">
    <wsdl:part element=\"tns:getAttCert\" name=\"parameters\"/>
  </wsdl:message>

  <wsdl:message name=\"getAttCertOutputMsg\">
    <wsdl:part element=\"tns:getAttCertResponse\" name=\"parameters\"/>
  </wsdl:message>
  
  <wsdl:message name=\"getHostInfoInputMsg\">
    <wsdl:part element=\"tns:getHostInfo\" name=\"parameters\"/>
  </wsdl:message>

  <wsdl:message name=\"getHostInfoOutputMsg\">
    <wsdl:part element=\"tns:getHostInfoResponse\" name=\"parameters\"/>
  </wsdl:message>

  <wsdl:message name=\"getTrustedHostInfoInputMsg\">
    <wsdl:part element=\"tns:getTrustedHostInfo\" name=\"parameters\"/>
  </wsdl:message>

  <wsdl:message name=\"getTrustedHostInfoOutputMsg\">
    <wsdl:part element=\"tns:getTrustedHostInfoResponse\" name=\"parameters\"/>
  </wsdl:message>

  <wsdl:message name=\"getAllHostsInfoInputMsg\">
    <wsdl:part element=\"tns:getAllHostsInfo\" name=\"parameters\"/>
  </wsdl:message>

  <wsdl:message name=\"getAllHostsInfoOutputMsg\">
    <wsdl:part element=\"tns:getAllHostsInfoResponse\" name=\"parameters\"/>
  </wsdl:message>

  <wsdl:portType name=\"AttributeAuthority\">
    <wsdl:operation name=\"getAttCert\">
      <wsdl:input message=\"tns:getAttCertInputMsg\"/>
      <wsdl:output message=\"tns:getAttCertOutputMsg\"/>
    </wsdl:operation>

    <wsdl:operation name=\"getHostInfo\">
      <wsdl:input message=\"tns:getHostInfoInputMsg\"/>
      <wsdl:output message=\"tns:getHostInfoOutputMsg\"/>
    </wsdl:operation>

    <wsdl:operation name=\"getTrustedHostInfo\">
      <wsdl:input message=\"tns:getTrustedHostInfoInputMsg\"/>
      <wsdl:output message=\"tns:getTrustedHostInfoOutputMsg\"/>
    </wsdl:operation>

    <wsdl:operation name=\"getAllHostsInfo\">
      <wsdl:input message=\"tns:getAllHostsInfoInputMsg\"/>
      <wsdl:output message=\"tns:getAllHostsInfoOutputMsg\"/>
    </wsdl:operation>

  </wsdl:portType>

  <wsdl:binding name=\"AttributeAuthorityBinding\" type=\"tns:AttributeAuthority\">
    <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
     
    <wsdl:operation name=\"getAttCert\">
      <soap:operation soapAction=\"getAttCert\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>

    <wsdl:operation name=\"getHostInfo\">
      <soap:operation soapAction=\"getHostInfo\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output> 
    </wsdl:operation>

    <wsdl:operation name=\"getTrustedHostInfo\">
      <soap:operation soapAction=\"getTrustedHostInfo\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output> 
    </wsdl:operation>

    <wsdl:operation name=\"getAllHostsInfo\">
      <soap:operation soapAction=\"getAllHostsInfo\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use=\"literal\"/>
      </wsdl:output> 
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name=\"AttributeAuthorityService\">
    <wsdl:documentation>NERC Data Grid Attribute Authority web service</wsdl:documentation>
    <wsdl:port binding=\"tns:AttributeAuthorityBinding\" name=\"AttributeAuthority\">
      <soap:address location=\"http://localhost:5000\"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='', **kw):
        ServiceSOAPBinding.__init__(self, post)
        if kw.has_key('impl'):
            self.impl = kw['impl']
        self.auth_method_name = None
        if kw.has_key('auth_method_name'):
            self.auth_method_name = kw['auth_method_name']
    def authorize(self, auth_info, post, action):
        if self.auth_method_name and hasattr(self.impl, self.auth_method_name):
            return getattr(self.impl, self.auth_method_name)(auth_info, post, action)
        else:
            return 1

    def soap_getAttCert(self, ps):
        self.request = ps.Parse(getAttCertInputMsg.typecode)
        parameters = (self.request._userId, self.request._userX509Cert, self.request._userAttCert)

        # If we have an implementation object use it
        if hasattr(self,'impl'):
            parameters = self.impl.getAttCert(parameters[0],parameters[1],parameters[2])

        result = getAttCertOutputMsg()
        # If we have an implementation object, copy the result 
        if hasattr(self,'impl'):
            # Should have a tuple of 2 args
            result._attCert = parameters[0]
            result._msg = parameters[1]
        return result

    soapAction['getAttCert'] = 'soap_getAttCert'
    root[(getAttCertInputMsg.typecode.nspname,getAttCertInputMsg.typecode.pname)] = 'soap_getAttCert'

    def soap_getHostInfo(self, ps):
        self.request = ps.Parse(getHostInfoInputMsg.typecode)

        # If we have an implementation object use it
        if hasattr(self,'impl'):
            parameters = self.impl.getHostInfo()

        result = getHostInfoOutputMsg()
        # If we have an implementation object, copy the result 
        if hasattr(self,'impl'):
            # Should have a tuple of 7 args
            result._hostname = parameters[0]
            result._siteName = parameters[1]
            result._aaURI = parameters[2]
            result._aaDN = parameters[3]
            result._loginURI = parameters[4]
            result._loginServerDN = parameters[5]
            result._loginRequestServerDN = parameters[6]
        return result

    soapAction['getHostInfo'] = 'soap_getHostInfo'
    root[(getHostInfoInputMsg.typecode.nspname,getHostInfoInputMsg.typecode.pname)] = 'soap_getHostInfo'

    def soap_getTrustedHostInfo(self, ps):
        self.request = ps.Parse(getTrustedHostInfoInputMsg.typecode)
        parameters = self.request._role

        # If we have an implementation object use it
        if hasattr(self,'impl'):
            parameters = self.impl.getTrustedHostInfo(parameters)

        result = getTrustedHostInfoOutputMsg()
        # If we have an implementation object, copy the result 
        if hasattr(self,'impl'):
            result._trustedHosts = parameters
        return result

    soapAction['getTrustedHostInfo'] = 'soap_getTrustedHostInfo'
    root[(getTrustedHostInfoInputMsg.typecode.nspname,getTrustedHostInfoInputMsg.typecode.pname)] = 'soap_getTrustedHostInfo'

    def soap_getAllHostsInfo(self, ps):
        self.request = ps.Parse(getAllHostsInfoInputMsg.typecode)

        # If we have an implementation object use it
        if hasattr(self,'impl'):
            parameters = self.impl.getAllHostsInfo()

        result = getAllHostsInfoOutputMsg()
        # If we have an implementation object, copy the result 
        if hasattr(self,'impl'):
            result._hosts = parameters
        return result

    soapAction['getAllHostsInfo'] = 'soap_getAllHostsInfo'
    root[(getAllHostsInfoInputMsg.typecode.nspname,getAllHostsInfoInputMsg.typecode.pname)] = 'soap_getAllHostsInfo'

