################################################## 
# VocabServerAPIService_messages.py 
# generated by ZSI.generate.wsdl2python
##################################################


from VocabServerAPIService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

whatListsRequest = urn_VocabServerAPI.whatLists().pyclass

whatListsResponse = urn_VocabServerAPI.whatListsResponse().pyclass

getListRequest = urn_VocabServerAPI.getList().pyclass

getListResponse = urn_VocabServerAPI.getListResponse().pyclass

verifyTermRequest = urn_VocabServerAPI.verifyTerm().pyclass

verifyTermResponse = urn_VocabServerAPI.verifyTermResponse().pyclass

pvMapRequest = urn_VocabServerAPI.pvMap().pyclass

pvMapResponse = urn_VocabServerAPI.pvMapResponse().pyclass

getPhenomDictRequest = urn_VocabServerAPI.getPhenomDict().pyclass

getPhenomDictResponse = urn_VocabServerAPI.getPhenomDictResponse().pyclass

whatListsCatRequest = urn_VocabServerAPI.whatListsCat().pyclass

whatListsCatResponse = urn_VocabServerAPI.whatListsCatResponse().pyclass

searchVocabRequest = urn_VocabServerAPI.searchVocab().pyclass

searchVocabResponse = urn_VocabServerAPI.searchVocabResponse().pyclass
