################################################## 
# Gatekeeper_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from Gatekeeper_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class GatekeeperServiceLocator:
    Gatekeeper_address = "http://localhost:5000"
    def getGatekeeperAddress(self):
        return GatekeeperServiceLocator.Gatekeeper_address
    def getGatekeeper(self, url=None, **kw):
        return GatekeeperBindingSOAP(url or GatekeeperServiceLocator.Gatekeeper_address, **kw)

# Methods
class GatekeeperBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb78a728c>
    def get(self, userX509Cert,userAttributeCertificate,geoserverRequest):

        request = getInputMsg()
        request._userX509Cert = userX509Cert
        request._userAttributeCertificate = userAttributeCertificate
        request._geoserverRequest = geoserverRequest

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="get", **kw)
        # no output wsaction
        response = self.binding.Receive(getOutputMsg.typecode)
        geoServerResponse = response._geoServerResponse
        return geoServerResponse

getInputMsg = ns0.get_Dec().pyclass

getOutputMsg = ns0.getResponse_Dec().pyclass
