################################################## 
# SimpleCA_client.py 
# generated by ZSI.generate.wsdl2python
##################################################



import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

from SimpleCA_messages import certRequest, certResponse

# Locator
class SimpleCAServiceLocator:
    SimpleCA_address = "http://localhost:5001"
    def getSimpleCAAddress(self):
        return SimpleCAServiceLocator.SimpleCA_address
    def getSimpleCA(self, url=None, **kw):
        return SimpleCABindingSOAP(url or SimpleCAServiceLocator.SimpleCA_address, **kw)

# Methods
class SimpleCABindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: <ZSI.wstools.WSDLTools.Message instance at 0xb6e3416c>
    def reqCert(self, x509CertReq):

        request = certRequest()
        request.x509CertReq = x509CertReq

        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="reqCert", **kw)
        # no output wsaction
        response = self.binding.Receive(certResponse.typecode)
        x509Cert = response.x509Cert
        errMsg = response.errMsg
        return x509Cert,errMsg
