<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="SimpleCA"
 xmlns="http://schemas.xmlsoap.org/wsdl/"
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:tns="urn:ZSI:SimpleCA"
 xmlns:wsu="http://schemas.xmlsoap.org/ws/2002/07/utility"
 targetNamespace="urn:ZSI:SimpleCA">

  <wsdl:types>
    <xsd:schema>
      <xsd:element name="signCertReq">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="x509CertReq" type="xsd:string" minOccurs="1" maxOccurs="1"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="signCertReqResponse">
        <xsd:complexType>
		  <xsd:sequence>
	        <xsd:element name="x509Cert" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		  </xsd:sequence>
		</xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="signCertReq">
    <wsdl:part name="parameters" element="signCertReq"/>
  </wsdl:message>

  <wsdl:message name="signCertReqResponse">
    <wsdl:part name="parameters" element="signCertReqResponse"/>
  </wsdl:message>

  <wsdl:portType name="SimpleCA">
    <wsdl:operation name="signCertReq">
      <wsdl:input message="tns:signCertReqInputMsg"/>
      <wsdl:output message="tns:signCertReqOutputMsg"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="SimpleCABinding" type="tns:SimpleCA">
    <soap:binding
     style="document"
     transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="signCertReq">
      <soap:operation soapAction="signCertReq"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="SimpleCAService">
    <wsdl:documentation>SimpleCA web service</wsdl:documentation>
    <wsdl:port name="SimpleCA" binding="tns:SimpleCABinding">
      <soap:address location="http://localhost:5001"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
